/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e225718;
import static org.junit.jupiter.api.Assertions.assertEquals;




import org.junit.jupiter.api.Test;



public class GameTest {
    //ユニットテスト何かくか
    @Test
    void gamingtest(){
        Game demoplayer = new Game("kento");
        assertEquals(demoplayer.getName(), "kento");

    }
}